config/routes.rb
Advert::Application.routes.draw do
  get "ads/new"

  resources :users
  resources :ads, only: [:create,:index, :destroy]
  resources :visitors
  root 'welcome#index'
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',  via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  get 'admin' => 'admin#dashboard', as: :admin

  

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: {maximum: 50}
 # scope :approved, -> { where(approved: true) }
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ads
  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  http_basic_authenticate_with name: "cp", password: "secret"
  def dashboard
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
 #before_action :signed_in_user, only: [:create,:index, :destroy]

  def index
    if params[:approved] == "false"
      @ads = Ad.find_all_by_approved(false)
    else
    @ads = Ad.all
    end
  end
  def create
    @ad = current_user.ads.build(ad_params)
    if @ad.save
      redirect_to root_path
          else
      render 'welcome/index'
    end
  end
  def destroy
    Ad.find(params[:id]).destroy
    redirect_to ads_url

  end
  private
  def ad_params
    params.require(:ad).permit(:title, :description,:contact_details, :approved)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      render 'new'
    end

  end
  def destroy
    sign_out
    redirect_to root_url

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
 def show
   @user = User.find(params[:id])
   @ads = @user.ads
 end
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
    redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def new

  end
  def index

  end
  def show

  end
  def create
    @visitor = Visitor.new(visitor_params)
     @visitor.save
      redirect_to @visitor
  end

  private

  def visitor_params
    params.require(:visitor).permit(:name, :email)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @ad = current_user.ads.build if signed_in?
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end
  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end
  def current_user
  remember_token = User.encrypt(cookies[:remember_token])
  @current_user ||= User.find_by(remember_token: remember_token)
  end
  def current_user?(user)
    user == current_user
  end
  def signed_in_user
    unless signed_in?
     # store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/dashboard.html.erb
<h1>Admin Dashboard</h1>
<li><%= link_to "Ads", ads_path %></li>

app/views/ads/_ad.html.erb
<li>
  <%= ad.title %>
</li>

app/views/ads/index.html.erb
<h1>All Ads</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Contact Details</th>
    <th>User_id</th>
    <th></th>
    <th></th>

  </tr>
  <% @ads.each do |ad| %>
      <tr>

        <td><%= ad.title %></td>
        <td><%= ad.description %></td>
        <td><%= ad.contact_details %></td>
        <td><%= ad.user_id %></td>
        <td><%= link_to "delete", ad, method: :delete,
                    data: { confirm: "You sure?" } %>  </td>
         <td>

             <%= label_tag :approved, "Approved" %>
             <%= check_box_tag :approved %>

         </td>

      </tr>
  <% end %>
</table><br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Advert</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
  <div id="wrapper-bgbtm">
    <div id="header">
      <div id="logo">
        <h1><a href="#">Wood Working </a></h1>
        <p>template design by <a href="http://www.freecsstemplates.org/" rel="nofollow">FreeCSSTemplates.org</a></p>
      </div>
    </div>
    <!-- end #header -->
    <div id="menu">
      <ul>
        <li class="current_page_item"><a href="#">Homepage</a></li>
         <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
        <li><%= link_to "Advertisements", ads_path %></li>
        <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>

                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>

            </li>
        <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
    </div>
    <!-- end #menu -->
    <div id="page">
      <div id="page-bgtop">
        <div id="page-bgbtm">
          <%= yield %>
          <!-- end #content -->
          <div id="sidebar">
            <div id="search">
              <h2>Search</h2>
              <form method="get" action="">
                <fieldset>
                  <input type="text" name="s" id="search-text" size="15" value="enter keywords here..." />
                  <input type="submit" id="search-submit" value="GO" />
                </fieldset>
              </form>
            </div>
            <ul>
              <li>
                <h2>Aliquam tempus</h2>
                <p>Mauris vitae nisl nec metus placerat perdiet est. Phasellus dapibus semper consectetuer hendrerit.</p>
              </li>
              <li>
                <h2>Categories</h2>
                <ul>
                  <li><a href="#">Aliquam libero</a></li>
                  <li><a href="#">Consectetuer adipiscing elit</a></li>
                  <li><a href="#">Metus aliquam pellentesque</a></li>
                  <li><a href="#">Suspendisse iaculis mauris</a></li>
                  <li><a href="#">Urnanet non molestie semper</a></li>
                  <li><a href="#">Proin gravida orci porttitor</a></li>
                </ul>
              </li>
              <li>
                <h2>Blogroll</h2>
                <ul>
                  <li><a href="#">Aliquam libero</a></li>
                  <li><a href="#">Consectetuer adipiscing elit</a></li>
                  <li><a href="#">Metus aliquam pellentesque</a></li>
                  <li><a href="#">Suspendisse iaculis mauris</a></li>
                  <li><a href="#">Urnanet non molestie semper</a></li>
                  <li><a href="#">Proin gravida orci porttitor</a></li>
                </ul>
              </li>
              <li>
                <h2>Archives</h2>
                <ul>
                  <li><a href="#">Aliquam libero</a></li>
                  <li><a href="#">Consectetuer adipiscing elit</a></li>
                  <li><a href="#">Metus aliquam pellentesque</a></li>
                  <li><a href="#">Suspendisse iaculis mauris</a></li>
                  <li><a href="#">Urnanet non molestie semper</a></li>
                  <li><a href="#">Proin gravida orci porttitor</a></li>
                </ul>
              </li>
            </ul>
          </div>
          <!-- end #sidebar -->
          <div style="clear: both;">&nbsp;</div>
        </div>
      </div>
    </div>
    <!-- end #page -->
    <div id="footer">
      <p>Copyright (c) 2011 Sitename.com. All rights reserved. Design by <a href="http://www.freecsstemplates.org/" rel="nofollow">FreeCSSTemplates.org</a>.</p>
    </div>
    <!-- end #footer -->
  </div>
</div>


</body>
</html>

app/views/shared/_ad_form.html.erb
<%= form_for(@ad) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <p>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :description  %>
      <%= f.text_area :description %>
    </p>
    <p>
      <%= f.label :contact_details %>
      <%= f.text_area :contact_details %>
    </p>

    <p>
    <%= f.submit "Post" %>
<% end %>


app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>


app/views/shared/_user_info.html.erb
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.ads.count, "ad") %>
</span>

app/views/users/new.html.erb
<h1>SignUp Here</h1>
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
    </p>
    <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<% if @user.ads.any? %>
    <table>
      <tr>
        <th>Title</th>
      </tr>
      <tr>
      <td>
     <ol><%= render @ads %></ol>
      </td>
      </tr>
    </table>
<% end %>
<%= link_to "create new Ad", root_url %>

app/views/visitors/index.html.erb
<%= link_to "Advertisements", ads_path %> <br/><br>


app/views/visitors/new.html.erb
<%= form_for :visitor, url: visitors_path do |f| %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :email  %>
      <%= f.text_field :email %>
    </p>

    <p>
      <%= f.submit "Post Contact_Details" %>
    </p>
<% end %>

app/views/visitors/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @visitor.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @visitor.email %>
</p>

app/views/welcome/index.html.erb
<% if signed_in? %>
    <div class="row">
      <aside class="span4">
        <section>
          <%= render 'shared/user_info' %>
        </section>
        <section>
          <%= render 'shared/ad_form' %>
        </section>
      </aside>
    </div>
<% else %>

    <h1>Welcome to my website</h1>
<h1><%= link_to "Sign up now!", signup_path %> </h1>
<div id="content">
  <div class="post">
    <h2 class="title"><a href="#">Welcome to Wood Working </a></h2>
    <p class="meta">Posted by <a href="#">Someone</a> on July 10, 2011
      &nbsp;&bull;&nbsp; <a href="#" class="comments">Comments (64)</a> &nbsp;&bull;&nbsp; <a href="#" class="permalink">Full article</a></p>
    <div class="entry">
      <p><%= image_tag "img02.jpg", width:143, height:143, alt:"", class:"alignleft border" %>This is <strong>Wood Working </strong>, a free, fully standards-compliant CSS template designed by <a href="http://www.freecsstemplates.org/" rel="nofollow">FreeCSSTemplates.org</a>.  The picture in this template is from <a href="#">PDPhoto.org</a>. This free template is released under a <a href="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attributions</a> license, so you’re pretty much free to do whatever you want with it (even use it commercially) provided you keep the links in the footer intact. Aside from that, have fun with it :)</p>
      <p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum ipsum. Proin imperdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in felis. Donec ut ante. In id eros. Suspendisse lacus turpis at sem. Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. </p>
    </div>
  </div>
  <div class="post">
    <h2 class="title"><a href="#">Lorem ipsum sed aliquam</a></h2>
    <p class="meta">Posted by <a href="#">Someone</a> on July 8, 2011
      &nbsp;&bull;&nbsp; <a href="#" class="comments">Comments (64)</a> &nbsp;&bull;&nbsp; <a href="#" class="permalink">Full article</a></p>
    <div class="entry">
      <p><%= image_tag "img03.jpg",width:143, height:143, alt:"", class:"alignleft border" %>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Phasellus <a href="#">dapibus semper urna</a>. Pellentesque ornare, consectetuer nisl felis ac diam. Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at,  non, purus. Mauris vitae nisl nec metus  consectetuer.</p>

    </div>
  </div>
  <div class="post">
    <h2 class="title"><a href="#">Consectetuer hendrerit urnaelit</a></h2>
    <p class="meta">Posted by <a href="#">Someone</a> on July 8, 2011
      &nbsp;&bull;&nbsp; <a href="#" class="comments">Comments (64)</a> &nbsp;&bull;&nbsp; <a href="#" class="permalink">Full article</a></p>
    <div class="entry">
      <p><%= image_tag "img04.jpg", width:143, height:143, alt:"", class:"alignleft border" %>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc. Proin imperdiet est. Pellentesque ornare eleifend nunc. Donec ipsum. Proin imperdiet est. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc. </p>
    </div>
  </div>
  <div class="post">
    <h2 class="title"><a href="#">Phasellus pellentesque turpis </a></h2>
    <p class="meta">Posted by <a href="#">Someone</a> on July 8, 2011
      &nbsp;&bull;&nbsp; <a href="#" class="comments">Comments (64)</a> &nbsp;&bull;&nbsp; <a href="#" class="permalink">Full article</a></p>
    <div class="entry">
      <p><%= image_tag "img02.jpg", width:143, height:143, alt:"", class:"alignleft border" %>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc. Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. </p>
    </div>
  </div>
</div>
<% end %>